/**
 * Symptom Entry Domain Models
 * 
 * This module defines the core data structures for symptom entries within
 * the health domain. These models represent the business entities and data
 * transfer objects used throughout the symptom management system.
 * 
 * The models follow Domain-Driven Design (DDD) principles, clearly separating
 * entities (with identity) from value objects and data transfer objects.
 * 
 * Features:
 * - Type-safe data structures
 * - Clear separation between entities and DTOs
 * - Comprehensive documentation for each field
 * - Validation-ready interfaces
 */

/**
 * Symptom Entry Entity
 * 
 * Represents a complete symptom entry as stored in the database and used
 * throughout the application. This is a domain entity with a unique identity
 * that persists over time.
 * 
 * The entity includes all fields that are generated or managed by the system,
 * such as unique identifiers and timestamps.
 * 
 * @interface SymptomEntry
 */
export interface SymptomEntry {
  /** 
   * Unique identifier for the symptom entry
   * Generated by the database (UUID format)
   */
  id: string;
  
  /** 
   * The user's detailed description of their symptoms
   * Free-form text input from the user
   */
  symptoms: string;
  
  /** 
   * Timestamp when the symptom entry was created
   * Automatically set by the database on insertion
   */
  createdAt: Date;
}

/**
 * Create Symptom Entry Data Transfer Object
 * 
 * Represents the minimal data required to create a new symptom entry.
 * This DTO is used for API requests and form submissions, containing only
 * the user-provided data without system-generated fields.
 * 
 * This is a value object that focuses on data transfer rather than identity,
 * making it ideal for API boundaries and validation scenarios.
 * 
 * @interface CreateSymptomEntryDTO
 */
export interface CreateSymptomEntryDTO {
  /** 
   * The user's description of their symptoms
   * Required field with business validation rules applied
   * - Minimum length: 5 characters
   * - Maximum length: 2000 characters
   * - Must not be empty or whitespace-only
   */
  symptoms: string;
}

/**
 * Update Symptom Entry Data Transfer Object
 * 
 * Represents the data that can be modified in an existing symptom entry.
 * Currently, symptom entries are designed to be immutable after creation
 * for data integrity, but this interface is provided for future extensibility.
 * 
 * @interface UpdateSymptomEntryDTO
 */
export interface UpdateSymptomEntryDTO {
  /** 
   * Updated symptom description
   * Optional field for partial updates
   */
  symptoms?: string;
}

/**
 * Symptom Entry Query Parameters
 * 
 * Represents the parameters that can be used to query symptom entries.
 * Useful for filtering, sorting, and pagination operations.
 * 
 * @interface SymptomEntryQueryParams
 */
export interface SymptomEntryQueryParams {
  /** 
   * Maximum number of entries to return
   * Used for pagination
   */
  limit?: number;
  
  /** 
   * Number of entries to skip
   * Used for pagination offset
   */
  offset?: number;
  
  /** 
   * Filter entries created after this date
   * Useful for date range queries
   */
  createdAfter?: Date;
  
  /** 
   * Filter entries created before this date
   * Useful for date range queries
   */
  createdBefore?: Date;
  
  /** 
   * Search term to filter symptoms by content
   * Performs case-insensitive text search
   */
  searchTerm?: string;
}